version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      go-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      go-minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      docker-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      docker-minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Kolkata
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps
